Update training controller service to fetch parameters from KV and launch training job
rancher/opni-training-controller pull request #21
Opened 2023-03-28 15:19 UTC by AmartC

2023-03-28 22:04 UTC, tybalex requested changes
In general can you please add description of `what does this PR do`

2023-03-28 22:04 UTC, tybalex commented on training_controller/main.py
> +    updated_workload_parameters = copy.deepcopy(workload_parameters)
redundant deep copy? see line 133

2023-03-28 22:04 UTC, tybalex commented on training_controller/main.py
> +            asyncio.sleep(30)
await

2023-03-28 22:04 UTC, tybalex commented on training_controller/main.py
>          if gpu_service_status == "running":
what happens if the gpu_service is not `running` within 15 retries? would the UI be able to get this info?

2023-03-28 22:04 UTC, tybalex commented on training_controller/main.py
> +        workload_parameters = workload_parameters_dict["workloads"]
* now that we have natsKV, should probably not using global variable `workload_parameters_dict` anymore, instead just read from natsKV.

2023-03-28 22:04 UTC, tybalex commented on training_controller/main.py
>      try:
rename this function or add docstrings to match its new activity

2023-03-28 22:04 UTC, tybalex commented on training_controller/main.py
> +            await update_opensearch(training_payload["workloads"])
is it still necessary to push to OpenSearch

2023-03-29 19:25 UTC, AmartC commented on training_controller/main.py
>          if gpu_service_status == "running":
No right now, it wouldn't get that information right now. We can look to add logic in future if this step fails.

2023-03-30 23:51 UTC, tybalex approved these changes
lg

2023-03-31 00:02 UTC, merged