rework training controller to gpu-service.
rancher/opni-training-controller pull request #3
Opened 2021-07-20 05:05 UTC by tybalex

2021-07-27 17:55 UTC, AmartC submitted a review, later dismissed

2021-07-28 00:25 UTC, sanjay920 requested changes

2021-07-28 00:25 UTC, sanjay920 commented on training_controller/main.py
> +gpu_training_request = 0
move global variable to the top

2021-07-28 13:10 UTC, tybalex commented on training_controller/main.py
> +gpu_training_request = 0
fixed.

2021-07-28 16:44 UTC, sanjay920 approved these changes

2021-07-28 21:45 UTC, AmartC approved these changes

2021-07-29 02:31 UTC, merged