Remove s3 for training data
rancher/opni-training-controller pull request #7
Opened 2021-08-13 02:34 UTC by dbason

Just dump es data and use windows locally

2021-08-13 05:10 UTC, sanjay920 requested changes

2021-08-13 05:10 UTC, sanjay920 commented on training_controller/prepare_training_logs.py
> +        self.WORKING_DIR = TRAINING_DATA_PATH
no need to have this be a global var just set to `os.getenv("TRAINING_DATA_PATH", "/var/opni-data")`

2021-08-13 08:44 UTC, tybalex commented
basically it only downloads from ES but no longer upload to S3, am I right?

2021-08-15 21:10 UTC, dbason commented
> basically it only downloads from ES but no longer upload to S3, am I right?

Correct

2021-08-17 02:18 UTC, AmartC approved these changes
LGTM

2021-08-17 14:55 UTC, sanjay920 approved these changes

2021-08-17 20:13 UTC, merged